Ref [TASK][51875, 51876, 51877] Init Model, Database
awesome-academy/marvel-app-2 pull request #5
Opened 2022-08-19 01:31 UTC by minhnn-1279

[Task #51875: Create Model to save Data](https://edu-redmine.sun-asterisk.vn/issues/51875)
[Task #51876: Create SQLite Database and Shared Preferences file](https://edu-redmine.sun-asterisk.vn/issues/51876)
[Task #51877: Create HTTP Url Connection](https://edu-redmine.sun-asterisk.vn/issues/51877)

What:
- Create Model to save Data
- Create SQLite Database and Shared Preferences file
- Create HTTP Url Connection

2022-08-19 03:21 UTC, cuongvd-1287 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/data/repository/source/remote/fetchjson/GetJsonFromUrl.kt
> +import java.util.concurrent.*
Không import *

2022-08-19 03:21 UTC, cuongvd-1287 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/data/repository/source/remote/fetchjson/ParseJson.kt
> +import android.util.Log
xóa Log

2022-08-19 03:22 UTC, cuongvd-1287 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/screen/loading/LaunchActivity.kt
> +import java.util.*
.

2022-08-19 03:25 UTC, cuongvd-1287 commented on app/src/main/res/values/colors.xml
>      <color name="PrimaryColor">#FF202020</color>
thêm color_ trước màu

2022-08-19 03:37 UTC, truongtv-1281 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/data/repository/source/local/database/MyDatabase.kt
> +    version: Int = 1
hard code

2022-08-19 03:37 UTC, truongtv-1281 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/util/base/BaseFragment.kt
> +    protected val mContext: Context
sắp xếo thứ tự, blank line

2022-08-19 03:37 UTC, truongtv-1281 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/util/base/BaseFragment.kt
>      abstract fun initData()
blank line

2022-08-19 03:37 UTC, truongtv-1281 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/util/constant/Constant.kt
> +    const val TYPE_WIKI_URL = "wiki"
tách constant theo yêu cầu sử dụng

2022-08-19 06:44 UTC, cuongvd-1287 approved these changes

2022-08-19 06:54 UTC, truongtv-1281 approved these changes

2022-08-19 08:31 UTC, daolq-2712 requested changes
Pls check my comments!

2022-08-19 08:31 UTC, daolq-2712 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/data/repository/source/local/database/MyDatabase.kt
> +    companion object {
@minhnn-1279 
Các ``companion object`` naỳ mình move ở cuối file e nhé

> Nội dung của một lớp được sắp xếp theo thứ tự sau:
> 
> 1. Khai báo thuộc tính (Property declarations) và khối khởi tạo (initializer blocks)
> 2. Các hàm tạo phụ (Secondary constructors)
> 3. Khai báo các method
> 4. Companion object

ref: https://github.com/framgia/coding-standards/blob/master/vn/android/coding_convention_android_kotlin.md#class-layout

2022-08-19 08:31 UTC, daolq-2712 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/util/base/BaseFragment.kt
> +    protected val mViewBinding: VBinding
không dùng đến -> xóa đi e

2022-08-19 08:31 UTC, daolq-2712 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/util/base/BaseFragment.kt
> +    protected val mContext: Context
biến thì khai báo ở đầu class & coding convension của cty mình không dùng tiền tố ``m`` -> đổi thành ``context`` e nhé!


https://github.com/framgia/coding-standards/blob/master/vn/android/coding_convention_android_kotlin.md#class-layout

2022-08-19 08:31 UTC, daolq-2712 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/util/base/BaseFragment.kt
> +    protected val mContext: Context
cơ mà biến này anh chưa thấy dùng => remove

2022-08-19 08:31 UTC, daolq-2712 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/util/constant/Constant.kt
> +    const val REQUEST_CODE_OK = 200
remove dòng này e nhé!

mình dùng ``HttpURLConnection.HTTP_OK``

2022-08-19 09:18 UTC, minhnn-1279 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/util/base/BaseFragment.kt
> +    protected val mContext: Context
Dạ em dùng ở đoạn sử dụng Glide mình truyền context vào luôn ạ, vì thường hay load ảnh Glide ở adapter mà em ko lấy được cái context ạ

2022-08-19 09:55 UTC, minhnn-1279 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/util/base/BaseFragment.kt
> +    protected val mViewBinding: VBinding
dạ cái này em dùng để gọi đối tượng binding tại lớp con ạ thay vì mình tạo lại đối tượng binding tại mỗi file ạ. Phần này em sẽ sử dụng sau ạ

2022-08-20 13:13 UTC, daolq-2712 approved these changes
OK!

2022-08-20 13:13 UTC, merged