Update feature character screen, detail character screen
awesome-academy/marvel-app-2 pull request #6
Opened 2022-08-26 07:53 UTC by nguyennhatminh230801

[Feature #51912: Character Screen](https://edu-redmine.sun-asterisk.vn/issues/51912)

What:
- Create UI for Character Screen
- Fetch data from API, Create Adapter
- Handle Event for Character Screen

![image](https://user-images.githubusercontent.com/57132619/186851812-01892a41-b492-4258-ac7b-493555840aaf.png)
Image character

![image](https://user-images.githubusercontent.com/57132619/186851912-1b6cb55a-4375-4f91-b280-b791d828a1cf.png)
Detail image character

2022-08-26 08:29 UTC, cuongvd-1287 requested changes

2022-08-26 08:29 UTC, cuongvd-1287 commented on app/src/main/res/layout/character_item_layout.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
thêm dòng trống

2022-08-26 08:29 UTC, cuongvd-1287 commented on app/src/main/res/layout/detail_character_fragment.xml
> +</ScrollView>
.

2022-08-26 08:29 UTC, cuongvd-1287 commented on app/src/main/res/layout/menu_item_layout.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
.

2022-08-26 08:36 UTC, truongtv-1281 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/data/repository/source/local/CharacterLocalDataSource.kt
> +    private val context: Context
k truyền context vào constructer

2022-08-26 08:36 UTC, truongtv-1281 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/screen/mainscreen/MenuItemAdapter.kt
> +    inner class ViewHolder(binding: MenuItemLayoutBinding) : RecyclerView.ViewHolder(binding.root)
inner class đúng trước companion object

2022-08-26 08:36 UTC, truongtv-1281 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/util/DTOItemAdapter.kt
> +    inner class ViewHolder(val binding: LayoutDtoItemBinding) :
.

2022-08-26 08:36 UTC, truongtv-1281 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/util/RecyclerTouchListener.kt
> +    context: Context,
context

2022-08-26 08:36 UTC, truongtv-1281 commented on app/src/main/res/layout/character_item_layout.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
end line

2022-08-26 08:36 UTC, truongtv-1281 commented on app/src/main/res/layout/detail_character_fragment.xml
> +            android:id="@+id/temp_event_list"
tên

2022-08-26 08:36 UTC, truongtv-1281 commented on app/src/main/res/layout/detail_character_fragment.xml
> +            android:id="@+id/temp_more_information"
.

2022-08-28 10:39 UTC, cuongvd-1287 approved these changes

2022-08-28 10:54 UTC, truongtv-1281 approved these changes

2022-08-28 11:13 UTC, gotech-mobiledev commented on app/src/main/java/com/nguyennhatminh614/marvelapp/util/DTOItemAdapter.kt
> +class DTOItemAdapter<T : DtoItem>(private val listDTOItem: List<T>) :
chú truyền qua constructor xong lúc nào cần change list là lại khởi tạo lại hả

2022-08-28 11:14 UTC, gotech-mobiledev commented on app/src/main/java/com/nguyennhatminh614/marvelapp/util/extensions/ImageViewExtension.kt
> +        .error(defaultImageID)
placeholder

2022-08-28 11:18 UTC, vietnh-1109 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/util/DTOItemAdapter.kt
> +class DTOItemAdapter<T : DtoItem>(private val listDTOItem: List<T>) :
ko truyền list qua adapter nhé , list của mình là mutable , nên sẽ viết 1 hàm để update , viết thế này lúc nào cần update là khởi tạo lại adapter à

2022-08-28 11:18 UTC, vietnh-1109 commented on app/src/main/java/com/nguyennhatminh614/marvelapp/util/extensions/ImageViewExtension.kt
> +        .error(defaultImageID)
place holder

2022-08-28 11:18 UTC, vietnh-1109 commented on app/src/main/res/drawable/bg_corner_top_right_5dp_bot_right_5dp.xml
> +        android:bottomRightRadius="5dp"/>
file dimens

2022-08-28 11:19 UTC, vietnh-1109 commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_height="match_parent"
bỏ overscroll mode đi , drawer mà để hiệu ứng này xấu lắm. hơn nữa viết layoutmanager trong này cho gọn

2022-08-29 07:01 UTC, merged